service: yahtzee-api
provider:
  name: aws
  httpApi:
    payload: '2.0'
    cors: true
  runtime: nodejs14.x
  region: eu-north-1
  environment: ${file(config/env.yml):${opt:stage, self:provider.stage}}
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - 'dynamodb:PutItem'
      - 'dynamodb:GetItem'
      - 'dynamodb:Query'
      - 'dynamodb:Scan'
    Resource: arn:aws:dynamodb:eu-north-1:922811907793:table/Yahtzee

layers:
  apiLayer:
    path: layer
    description: The Node Modules
    retain: false

functions:
  hello: ${file(config/hello.yml)}
  createGame: ${file(config/createGame.yml)}
  joinGame: ${file(config/joinGame.yml)}

package:
  exclude:
    - .*
    - pnpm-lock.yaml
    - package-lock.json
    - config/**
    - src/**
  excludeDevDependencies: false
  individually: true

custom:
  stage: ${opt:stage, self:provider.stage}
